# Generated by Django 4.1.6 on 2023-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('pan', models.IntegerField(blank=True)),
                ('locality', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('profile', models.ImageField(upload_to='profileimg')),
                ('file', models.FileField(upload_to='doc')),
            ],
        ),
    ]
